/*
 * This source file was generated by the Gradle 'init' task
 */
package uk.co.nickhowes

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions
import org.testcontainers.junit.jupiter.*
import org.testcontainers.containers.PostgreSQLContainer

@Testcontainers
class ResultSetInspectorTest {

    @Container
    private val pg = PostgreSQLContainer("postgres:16")
        
    @Test
    fun nonStreaming() {
        pg.createConnection("")!!.use { conn ->
            conn.createStatement().use { stmt ->
                stmt.executeQuery("select * from generate_series(1, 10000) as num").use { rs ->
                    assertNotNull(rs)
                    Assertions.assertEquals(10_000, ResultSetInspector.getNonCursorRowCount(rs))
                }
            }
        }
    }

    @Test
    fun streaming() {
        pg.createConnection("")!!.use { conn ->
            conn.autoCommit = false
            conn.createStatement().use { stmt ->
                stmt.fetchSize = 50
                stmt.executeQuery("select * from generate_series(1, 10000) as num").use { rs ->
                    assertNotNull(rs)
                    Assertions.assertEquals(-1, ResultSetInspector.getNonCursorRowCount(rs))
                }
            }
        }
    }


}
